stages:
  - Test
  - Build
  - Deployment

variables:
  IMAGE_NAME: hendranmanimaran21/smarter-than-ai-4
  IMAGE_TAG: recipe-app-1.0

test-all:
  image: maven:3.8.3-openjdk-17
  stage: Test
  tags: [maven]
  except:
    - master
  script:
    - mvn clean install
    - mvn test

test-unit:
  image: maven:3.8.3-openjdk-17
  stage: Test
  only:
    - master
  script:
    - mvn --version
    - mvn install -B
    - mvn test -Dtest=RecipeControllerTest
    - mvn test -Dtest=RecipePdfGeneratorTest
  artifacts:
    name: spring-boot-docker
    paths:
      - target/spring-boot-docker*.jar

build-image:
  stage: Build
  image: docker:24.0.2-cli
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --no-cache openssh-client
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSCODE 
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .  
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: Deployment
  before_script:
    - apk add --no-cache openssh-client
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@46.101.197.55 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASSCODE &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"


